// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778

package comps

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

const (
	Admin = "admin"
)

type AppState struct {
	User     string
	ViewMode string
}

func GuiComp() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form action=\"none\" name=\"state\" class=\"gui-comp\"><label for=\"user\">User</label> <input type=\"text\" id=\"user\" name=\"user\" placeholder=\"Email\" value=\"Admin\"> <label for=\"mode\">Mode</label> <select type=\"text\" id=\"mode\" name=\"password\" placeholder=\"Password\"><option value=\"2d\" selected>2d</option> <option value=\"3d\">3d</option></select> <button class=\"button -dynamic\" _=\"on click halt the event then call window.appState.update({user: document.getElementById(&#39;user&#39;).value, viewMode: document.getElementById(&#39;mode&#39;).value})\">Update</button></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
