// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.513
package comps

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func IndexComponent() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><link href=\"https://fonts.googleapis.com/css2?family=VT323&amp;display=swap\" rel=\"stylesheet\"><script src=\"https://unpkg.com/htmx.org@1.9.10\" integrity=\"sha384-D1Kt99CQMDuVetoL1lrYwg5t+9QdHe7NLX/SoJYkXDFfX37iInKRy5xLSi8nO7UC\" crossorigin=\"anonymous\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := ``
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</script><script src=\"https://unpkg.com/hyperscript.org@0.9.12\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var3 := ``
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</script><link rel=\"preconnect\" href=\"https://fonts.googleapis.com\"><link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin><style type=\"text/css\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var4 := `

            * {
                box-sizing: border-box;
                margin: 0;
                padding: 0;
            }

            body {
                font-family: 'VT323', monospace;
                font-size: 30px;
                height: 100vh;
                width: 100vw;
                overflow: hidden;
                opacity: 0;
            }

            body.loaded {
                opacity: 1;
                transition: opacity 0.2s ease-in-out;
            }

            #main {
                display: flex;
                height: 100%;
                /* align-content: center; */
                flex-direction: column;
                justify-content: center;
                align-items: center;
            }

            #grid-wrapper {
                display: grid;
                grid-template-columns: 1fr;
                grid-template-rows: max-content minmax(200px, 75%) max-content;
                grid-template-areas:
                    "header"
                    "map"
                    "options";
                width: 100%;
                max-height: 100%;
                justify-items: center;

                padding: 1em;
            }

            #header {
                position: relative;
                grid-area: header;
                bottom: 200px;
                display: flex;
                flex-direction: column;
                align-items: center;
                justify-content: space-between;
                padding: .6em;
                background-color: #fff;
                border-radius: .1em;
                border: 2px dotted #ccc;
                max-width: 20%;
                min-width: fit-content;
                z-index: 1;
                gap: .3em;
            }

            #header.loaded {
                bottom: -3px;
                transition: bottom 0.5s ease-in-out;
                transition-delay: 0.2s;
            }

            #header-actions {
                display: flex;
                flex-direction: row;
                align-items: center;
                justify-content: space-evenly;
                width: 100%;
                gap: .3em;
            }

            .button {
                border-radius: .1em;
                padding: 10px;
                border: 2px dotted #ccc;
                flex: 1;
                text-align: center;
                display: flex;
                align-items: center;
                justify-content: center;
                user-select: none;
            }

            .button:hover {
                cursor: pointer;
                background-color: #eee;
            }

            #tile-map {
                display: grid;
                grid-template-columns: repeat(30, 1fr);
                grid-template-rows: repeat(30, 1fr);
                aspect-ratio: 1 / 1; /* Ensures the width and height are equal */
                overflow: hidden;
                max-height: 100%;
                border-radius: 4px;
                border: 2px dotted #ccc;
                z-index: 1;
            }

            #tile-map.active {
                filter: drop-shadow(0 0 5px #333);
                cursor: crosshair;
            }

            .tile {
                display: block;
                user-select: none;
                color: transparent;
                min-width: 0px;
                min-height: 0px;
            }

            .tile:hover {
                filter: brightness(1.2);
                color: #999;
            border: 1px solid #eee;
            }

            .hght-0 {
                background-color: #000040; /* Deep ocean blue */
            }
            .hght-1 {
                background-color: #000080; /* Deep ocean blue */
            }
            .hght-2 {
                background-color: #0000CD; /* Darker blue */
            }
            .hght-3 {
                background-color: #1E90FF; /* Ocean blue */
            }
            .hght-4 {
                background-color: #2dc7ff; /* Ocean blue */
            }
            .hght-5 {
                background-color: #02a50d; /* Grassland green */
            }
            .hght-6 {
                background-color: #1d6200; /* Lighter green, representing plains or low hills */
            }
            .hght-7 {
                background-color: #6b4429; /* Dark brown, representing mountains */
            }
            .hght-8 {
                background-color: #838383; /* Light grey for lower mountains */
            }
            .hght-9 {
                background-color: #EEE; /* Snow white, highest peaks */
            }
            .hght-10 {
                background-color: #fff; /* Black, representing water */
            }

            #mapWrapper {
                display: flex;
                position: relative;
                flex-direction: row;
                align-items: center;
                justify-content: center;
                width: 100%;
                height: 100%;
                grid-area: map;
            }

            #sidebarBlock {
                width: 20%;
                height: 100%;
                overflow: hidden;
            }

            @media (orientation: landscape) {
                #grid-wrapper {
                    display: grid;
                    grid-template-rows: auto 1fr ;
                    grid-template-columns: 1fr auto;
                    grid-template-areas: "header header""map options";
                    background-color: red;
                }
                #options-group {
                    flex-direction: column !important;
                }
            }

        `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</style><script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var5 := `
            /**
             * @param {Event} e
             */
            function ReTrigger(e) {
                if ((e.type === "mouseover" || e.type === "click") && e.shiftKey === false && e.ctrlKey === false) {
                    return
                }
                var target = e.currentTarget;
                if (!(target instanceof HTMLElement)) {
                    return
                }
                if (target.nodeName !== "SPAN") {
                    return
                }
                var magnitude = 1;
                var shapeEvent = new CustomEvent("shape", {
                    detail: {
                        magnitude: e.shiftKey ? magnitude : -1 * magnitude,
                    },
                });
                target.dispatchEvent(shapeEvent);
            }
            htmx.on("htmx:load", function (e) {
                var element = e.detail.elt;

                // Add event listeners to all 'span.tile' elements within the loaded element
                element.querySelectorAll("span.tile").forEach(function (span) {
                    span.addEventListener("click", ReTrigger);
                    span.addEventListener("mouseover", ReTrigger);
                });

                // If the loaded element itself is a 'span.tile', add event listeners to it
                if (element.matches("span.tile")) {
                    element.addEventListener("click", ReTrigger);
                    element.addEventListener("mouseover", ReTrigger);
                }
            });
            // add control and shift keydown listeners
            window.addEventListener('keydown', (e) => {
                if (e.key === 'Shift') {
                    document.getElementById('lifting').classList.add('active')
                    document.getElementById('tile-map').classList.add('active')
                }
                if (e.key === 'Control') {
                    document.getElementById('tile-map').classList.add('active')
                    document.getElementById('lowering').classList.add('active')
                }
            })

            window.addEventListener('keyup', (e) => {
                if (e.key === 'Shift') {
                    document.getElementById('lifting').classList.remove('active')
                    document.getElementById('tile-map').classList.remove('active')
                }
                if (e.key === 'Control') {
                    document.getElementById('lowering').classList.remove('active')
                    document.getElementById('tile-map').classList.remove('active')
                }
            })
        `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</script><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var6 := `Document`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</title></head><body _=\"init add .loaded to me\"><div id=\"main\"><div id=\"grid-wrapper\"><div id=\"header\" _=\"init add .loaded to me\"><h1>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var7 := `HTMX Terragen`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var7)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</h1><div id=\"header-actions\"><div class=\"button\" hx-get=\"/new\" hx-target=\"#tile-map\" hx-swap=\"outerHTML\" hx-trigger=\"click\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var8 := `New Map`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var8)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div class=\"button\" hx-get=\"/display\" hx-target=\"#tile-map\" hx-swap=\"outerHTML\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var9 := `Get Last`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var9)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div></div><div id=\"mapWrapper\" _=\"on htmx:load add .loaded to #options then add .right to #header\"><div id=\"tile-map\" style=\"display:none;\"></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = OptionsComponent().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

// THESE ARE ONLY INITIAL CONCEPTS AND MAY NOT REFLECT FINAL COMPONENTS.
// 1.
// ┌──────────────────────┬─────────────────┬──────────────────────┐
// │                      │  HTMX TERRAGEN  │                      │
// │                      │                 │                      │
// │                      └─────────────────┘                      │
// │                                                               │
// │                                                               │ ┌───────────────┐
// │                                                               │ │               │
// │                                                               │ │   ┌───────┐   │
// │                                                               │ │   │   ▲   │   │
// │                                                               │ │   ├───────┤   │
// │               ┌──────────┐         ┌─────────┐                │ │   │   ▼   │   │
// │               │          │         │         │                │ │   └───────┘   │
// │               │          │         │         │                │ │               │
// │               │   new    │         │   last  │                │ │   ┌───────┐   │
// │               │          │         │         │                │ │   │       │   │
// │               │          │         │         │                │ │   │       │   │
// │               └──────────┘         └─────────┘                │ │   └───────┘   │
// │                                                               │ │               │
// │                                                               │ │   ┌───────┐   │
// │                                                               │ │   │       │   │
// │                                                               │ │   │       │   │
// │                                                               │ │   └───────┘   │
// │                                                               │ │               │
// │                                                               │ │ ┌───────────┐ │
// │                                                               │ │ │┼┼┼┼┼┼┼┼┼┼┼│ │
// │                                                               │ │ └───────────┘ │
// │                                                               │ │               │
// └───────────────────────────────────────────────────────────────┘ └───────────────┘
//  2. On new or last show world and move them to top
// ┌──────────────────────┬─────────────────┬──────────────────────┐
// │                      │  HTMX TERRAGEN  │                      │
// │                      │                 │                      │
// │                      └─────────────────┘                      │
// │                                                               │
// │                       ▲              ▲                        │  ┌───────────────┐
// │                       │              │                        │  │               │
// │                       │              │                        │  │   ┌───────┐   │
// │                       │              │                        │  │   │   ▲   │   │
// │                       │              │                        │  │   ├───────┤   │
// │               ┌───────┴──┐         ┌─┴───────┐                │  │   │   ▼   │   │
// │               │          │         │         │                │  │   └───────┘   │
// │               │          │         │         │                │  │               │
// │               │   new    │         │   last  │                │  │   ┌───────┐   │
// │               │          │         │         │                │  │   │       │   │
// │               │          │         │         │                │  │   │       │   │
// │               └──────────┘         └─────────┘                │  │   └───────┘   │
// │                                                               │  │               │
// │                                                               │  │   ┌───────┐   │
// │                                                               │  │   │       │   │
// │                                                               │  │   │       │   │
// │                                                               │  │   └───────┘   │
// │                                                               │  │               │
// │                                                               │  │ ┌───────────┐ │
// │                                                               │  │ │┼┼┼┼┼┼┼┼┼┼┼│ │
// │                                                               │  │ └───────────┘ │
// │                                                               │  │               │
// └───────────────────────────────────────────────────────────────┘  └───────────────┘
// 3. Bring in world options from off screen and move title right to above options
// ┌──────────────────────┬─────────────────┬──────────────────────┐
// │                      │  HTMX TERRAGEN  │                      │
// │                      │                 │                      │
// │                      ├────────┬────────┼──────►               │
// │                      │  new   │  last  │                      │
// │                      └────────┴────────┘                      │  ┌───────────────┐
// │                                                               │  │               │
// │                                                               │  │   ┌───────┐   │
// │                                                               │  │   │   ▲   │   │
// │                                                               │  │   ├───────┤   │
// │                                                               │  │   │   ▼   │   │
// │                                                               │  │   └───────┘   │
// │                                                               │  │               │
// │                                                               │  │   ┌───────┐   │
// │                                                    ◄──────────┼─ │   │       │   │
// │                                                               │  │   │       │   │
// │                                                               │  │   └───────┘   │
// │                                                               │  │               │
// │                                                               │  │   ┌───────┐   │
// │                                                               │  │   │       │   │
// │                                                               │  │   │       │   │
// │                                                               │  │   └───────┘   │
// │                                                               │  │               │
// │                                                               │  │ ┌───────────┐ │
// │                                                               │  │ │┼┼┼┼┼┼┼┼┼┼┼│ │
// │                                                               │  │ └───────────┘ │
// │                                                               │  │               │
// └───────────────────────────────────────────────────────────────┘  └───────────────┘
// 4. Final form of page
// ┌─────────────────────────────────────────────┬─────────────────┐
// │┼───────────────────────────────────────────┼│  HTMX TERRAGEN  │
// ││                                           ││                 │
// ││                                           │┼────────┬────────┤
// ││                                           ││  new   │  last  │
// ││                                           │┼────────┴────────┤
// ││                                           ││                 │
// ││                                           ││     ┌───────┐   │
// ││                                           ││     │   ▲   │   │
// ││                                           ││     ├───────┤   │
// ││                                           ││     │   ▼   │   │
// ││                                           ││     └───────┘   │
// ││                                           ││                 │
// ││                                           ││     ┌───────┐   │
// ││                                           ││     │       │   │
// ││                                           ││     │       │   │
// ││                                           ││     └───────┘   │
// ││                                           ││                 │
// ││                                           ││     ┌───────┐   │
// ││                                           ││     │       │   │
// ││                                           ││     │       │   │
// ││                                           ││     └───────┘   │
// ││                                           ││                 │
// ││                                           ││   ┌───────────┐ │
// ││                                           ││   │┼┼┼┼┼┼┼┼┼┼┼│ │
// ││                                           ││   └───────────┘ │
// │┼───────────────────────────────────────────┼│                 │
// └─────────────────────────────────────────────┴─────────────────┘
