// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.513
package comps

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func IndexComponent() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><link href=\"https://fonts.googleapis.com/css2?family=VT323&amp;display=swap\" rel=\"stylesheet\"><script src=\"/static/libs/htmx.min.js\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := ``
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</script><script src=\"/static/libs/hyperscript.min.js\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var3 := ``
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</script><link rel=\"preconnect\" href=\"https://fonts.googleapis.com\"><link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin><link rel=\"stylesheet\" href=\"/static/style.css\"><link rel=\"stylesheet\" href=\"/static/media.css\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var4 := `HTMX Terragen`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</title><script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var5 := `
                /**
                * @param {Event} e
                */
                function ReTrigger(e) {
                    if ((e.type === "mouseover" || e.type === "click") && e.shiftKey === false && e.ctrlKey === false) {
                        return
                    }
                    var target = e.currentTarget;
                    if (!(target instanceof HTMLElement)) {
                        return
                    }
                    if (target.nodeName !== "SPAN") {
                        return
                    }
                    var magnitude = 1;
                    var shapeEvent = new CustomEvent("shape", {
                        detail: {
                            magnitude: e.shiftKey ? magnitude : -1 * magnitude,
                        },
                    });
                    target.dispatchEvent(shapeEvent);
                }
                htmx.on("htmx:load", function (e) {
                    var element = e.detail.elt;

                    // Add event listeners to all 'span.tile' elements within the loaded element
                    element.querySelectorAll("span.tile").forEach(function (span) {
                        span.addEventListener("click", ReTrigger);
                        span.addEventListener("mouseover", ReTrigger);
                    });

                    // If the loaded element itself is a 'span.tile', add event listeners to it
                    if (element.matches("span.tile")) {
                        element.addEventListener("click", ReTrigger);
                        element.addEventListener("mouseover", ReTrigger);
                    }
                });
                // add control and shift keydown listeners
                window.addEventListener('keydown', (e) => {
                    if (e.key === 'Shift') {
                        document.getElementById('lifting').classList.add('active')
                        document.getElementById('tile-map').classList.add('active')
                    }
                    if (e.key === 'Control') {
                        document.getElementById('tile-map').classList.add('active')
                        document.getElementById('lowering').classList.add('active')
                    }
                })

                window.addEventListener('keyup', (e) => {
                    if (e.key === 'Shift') {
                        document.getElementById('lifting').classList.remove('active')
                        document.getElementById('tile-map').classList.remove('active')
                    }
                    if (e.key === 'Control') {
                        document.getElementById('lowering').classList.remove('active')
                        document.getElementById('tile-map').classList.remove('active')
                    }
                })
            `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</script></head><body _=\"init add .loaded to me\"><div id=\"main\"><div id=\"grid-wrapper\"><div id=\"header\" _=\"init add .loaded to me\"><h1>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var6 := `HTMX Terragen`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</h1><div id=\"header-actions\"><div class=\"button\" hx-get=\"/new\" hx-target=\"#tile-map\" hx-swap=\"outerHTML\" hx-trigger=\"click\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var7 := `New Map`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var7)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div class=\"button\" hx-get=\"/display\" hx-target=\"#tile-map\" hx-swap=\"outerHTML\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var8 := `Get Last`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var8)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div></div><div id=\"mapWrapper\"><div id=\"tile-map\" style=\"display:none;\"></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = OptionsComponent().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

// THESE ARE ONLY INITIAL CONCEPTS AND MAY NOT REFLECT FINAL COMPONENTS.
// 1.
// ┌──────────────────────┬─────────────────┬──────────────────────┐
// │                      │  HTMX TERRAGEN  │                      │
// │                      │                 │                      │
// │                      └─────────────────┘                      │
// │                                                               │
// │                                                               │ ┌───────────────┐
// │                                                               │ │               │
// │                                                               │ │   ┌───────┐   │
// │                                                               │ │   │   ▲   │   │
// │                                                               │ │   ├───────┤   │
// │               ┌──────────┐         ┌─────────┐                │ │   │   ▼   │   │
// │               │          │         │         │                │ │   └───────┘   │
// │               │          │         │         │                │ │               │
// │               │   new    │         │   last  │                │ │   ┌───────┐   │
// │               │          │         │         │                │ │   │       │   │
// │               │          │         │         │                │ │   │       │   │
// │               └──────────┘         └─────────┘                │ │   └───────┘   │
// │                                                               │ │               │
// │                                                               │ │   ┌───────┐   │
// │                                                               │ │   │       │   │
// │                                                               │ │   │       │   │
// │                                                               │ │   └───────┘   │
// │                                                               │ │               │
// │                                                               │ │ ┌───────────┐ │
// │                                                               │ │ │┼┼┼┼┼┼┼┼┼┼┼│ │
// │                                                               │ │ └───────────┘ │
// │                                                               │ │               │
// └───────────────────────────────────────────────────────────────┘ └───────────────┘
//  2. On new or last show world and move them to top
// ┌──────────────────────┬─────────────────┬──────────────────────┐
// │                      │  HTMX TERRAGEN  │                      │
// │                      │                 │                      │
// │                      └─────────────────┘                      │
// │                                                               │
// │                       ▲              ▲                        │  ┌───────────────┐
// │                       │              │                        │  │               │
// │                       │              │                        │  │   ┌───────┐   │
// │                       │              │                        │  │   │   ▲   │   │
// │                       │              │                        │  │   ├───────┤   │
// │               ┌───────┴──┐         ┌─┴───────┐                │  │   │   ▼   │   │
// │               │          │         │         │                │  │   └───────┘   │
// │               │          │         │         │                │  │               │
// │               │   new    │         │   last  │                │  │   ┌───────┐   │
// │               │          │         │         │                │  │   │       │   │
// │               │          │         │         │                │  │   │       │   │
// │               └──────────┘         └─────────┘                │  │   └───────┘   │
// │                                                               │  │               │
// │                                                               │  │   ┌───────┐   │
// │                                                               │  │   │       │   │
// │                                                               │  │   │       │   │
// │                                                               │  │   └───────┘   │
// │                                                               │  │               │
// │                                                               │  │ ┌───────────┐ │
// │                                                               │  │ │┼┼┼┼┼┼┼┼┼┼┼│ │
// │                                                               │  │ └───────────┘ │
// │                                                               │  │               │
// └───────────────────────────────────────────────────────────────┘  └───────────────┘
// 3. Bring in world options from off screen and move title right to above options
// ┌──────────────────────┬─────────────────┬──────────────────────┐
// │                      │  HTMX TERRAGEN  │                      │
// │                      │                 │                      │
// │                      ├────────┬────────┼──────►               │
// │                      │  new   │  last  │                      │
// │                      └────────┴────────┘                      │  ┌───────────────┐
// │                                                               │  │               │
// │                                                               │  │   ┌───────┐   │
// │                                                               │  │   │   ▲   │   │
// │                                                               │  │   ├───────┤   │
// │                                                               │  │   │   ▼   │   │
// │                                                               │  │   └───────┘   │
// │                                                               │  │               │
// │                                                               │  │   ┌───────┐   │
// │                                                    ◄──────────┼─ │   │       │   │
// │                                                               │  │   │       │   │
// │                                                               │  │   └───────┘   │
// │                                                               │  │               │
// │                                                               │  │   ┌───────┐   │
// │                                                               │  │   │       │   │
// │                                                               │  │   │       │   │
// │                                                               │  │   └───────┘   │
// │                                                               │  │               │
// │                                                               │  │ ┌───────────┐ │
// │                                                               │  │ │┼┼┼┼┼┼┼┼┼┼┼│ │
// │                                                               │  │ └───────────┘ │
// │                                                               │  │               │
// └───────────────────────────────────────────────────────────────┘  └───────────────┘
// 4. Final form of page
// ┌─────────────────────────────────────────────┬─────────────────┐
// │┼───────────────────────────────────────────┼│  HTMX TERRAGEN  │
// ││                                           ││                 │
// ││                                           │┼────────┬────────┤
// ││                                           ││  new   │  last  │
// ││                                           │┼────────┴────────┤
// ││                                           ││                 │
// ││                                           ││     ┌───────┐   │
// ││                                           ││     │   ▲   │   │
// ││                                           ││     ├───────┤   │
// ││                                           ││     │   ▼   │   │
// ││                                           ││     └───────┘   │
// ││                                           ││                 │
// ││                                           ││     ┌───────┐   │
// ││                                           ││     │       │   │
// ││                                           ││     │       │   │
// ││                                           ││     └───────┘   │
// ││                                           ││                 │
// ││                                           ││     ┌───────┐   │
// ││                                           ││     │       │   │
// ││                                           ││     │       │   │
// ││                                           ││     └───────┘   │
// ││                                           ││                 │
// ││                                           ││   ┌───────────┐ │
// ││                                           ││   │┼┼┼┼┼┼┼┼┼┼┼│ │
// ││                                           ││   └───────────┘ │
// │┼───────────────────────────────────────────┼│                 │
// └─────────────────────────────────────────────┴─────────────────┘
