# fly.toml app configuration file generated for ago on 2024-09-28T14:06:10+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ago'
primary_region = 'syd'

[build]
  [build.args]
    GO_VERSION = '1.21.5'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
